/**
 * Indus Asset Optimizer & Obfuscator Blueprint
 * 
 * Requirements:
 *   npm install sharp
 * 
 * Usage:
 *   node scripts/optimize-assets.js
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

// Configuration
const INPUT_DIR = path.join(__dirname, '../public/frames');
const OUTPUT_DIR = path.join(__dirname, '../public/frames_optimized');
const QUALITY = 75; // Enforce lossy 75% quality quantization
const CHROMA_SUBSAMPLING = '4:2:0';

// Synchronous obfuscation function matching frontend resolver
function getObfuscatedHash(filename) {
  // Use MD5 or a custom cryptographic hash to obfuscate sequential filenames
  return crypto
    .createHash('md5')
    .update(filename)
    .digest('hex');
}

// Main optimization runner
async function run() {
  let sharp;
  try {
    sharp = require('sharp');
  } catch (err) {
    console.error('Error: "sharp" library is required for compression.');
    console.log('Please install it using: npm install sharp');
    console.log('\n--- Obfuscation ONLY (Dry Run) ---');
  }

  if (!fs.existsSync(INPUT_DIR)) {
    console.error(`Input directory not found: ${INPUT_DIR}`);
    return;
  }

  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  const files = fs.readdirSync(INPUT_DIR).filter(file => file.endsWith('.webp'));
  console.log(`Found ${files.length} frames to process...`);

  for (let i = 0; i < files.length; i++) {
    const file = files[i];
    const inputPath = path.join(INPUT_DIR, file);
    
    // Obfuscate the filename (e.g. frame_000001 -> 3c59a721...)
    const nameWithoutExt = path.basename(file, '.webp');
    const obfuscatedName = `${getObfuscatedHash(nameWithoutExt)}.webp`;
    const outputPath = path.join(OUTPUT_DIR, obfuscatedName);

    if (sharp) {
      // Compress with 75% quality and chroma subsampling
      await sharp(inputPath)
        .webp({
          quality: QUALITY,
          smartSubsample: true, // Equivalent to chroma subsampling optimizations
          effort: 6
        })
        .toFile(outputPath);
    } else {
      // If sharp is not available, mock process (just rename files)
      fs.copyFileSync(inputPath, outputPath);
    }

    if ((i + 1) % 100 === 0 || i === files.length - 1) {
      console.log(`Processed ${i + 1}/${files.length} frames.`);
    }
  }

  console.log('\nOptimization & Obfuscation complete!');
  console.log(`Optimized files saved to: ${OUTPUT_DIR}`);
  console.log('\n======================================================');
  console.log('FRONTEND INTEGRATION BLUEPRINT:');
  console.log('Replace the `getFramePath` resolver in your hooks with:');
  console.log('------------------------------------------------------');
  console.log(`
import crypto from 'crypto'; // Or use a lightweight browser MD5 implementation

const getFramePath = (index: number) => {
  const frameNum = String(index).padStart(6, "0");
  const originalName = \`frame_\${frameNum}\`;
  
  // Hash matches the one generated by the script
  // To avoid Node "crypto" import overhead in the browser, 
  // you can use a simple JS MD5 helper function.
  const hash = md5(originalName); 
  return \`/frames/\${hash}.webp\`;
};
  `);
  console.log('======================================================');
}

run().catch(console.error);
